version: '3.8'

services:
  ocpi-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocpi-version-module
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ocpi-network

  caddy:
    image: caddy:2.7-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    restart: unless-stopped
    depends_on:
      - ocpi-api
    networks:
      - ocpi-network

volumes:
  caddy_data:
  caddy_config:

networks:
  ocpi-network:
    driver: bridge